import { TableTypesEnum } from './table-types-by-report-id'

const headerConfigsArr = [
  // 0: corporate-trust-services
  [
    'SHARECLASSNAME',
    'TANUMBER',
    'CUSIP',
    'SEVENDAYCURRENTYIELD',
    'SEVENDAYEFFECTIVEYIELD',
    'THIRTYDAYCURRENTYIELD',
    'THIRTYDAYEFFECTIVEYIELD',
    'DAILYWEIGHTEDAVERAGEMATURITY',
    'GROSSEXPENSERATIO',
    'NETEXPENSERATIO',
    'CUSTOMTRADINGDEADLINES',
    'FACTSHEETURL'
  ],
  // 1: gib
  [
    'SHARECLASSNAME',
    'TANUMBER',
    'CUSIP',
    'SEVENDAYCURRENTYIELD',
    'SEVENDAYPREWAIVERYIELD',
    'SEVENDAYEFFECTIVEYIELD',
    'THIRTYDAYCURRENTYIELD',
    'THIRTYDAYEFFECTIVEYIELD',
    'DAILYWEIGHTEDAVERAGEMATURITY',
    'GROSSEXPENSERATIO',
    'NETEXPENSERATIO',
    'CUSTOMTRADINGDEADLINES',
    'FACTSHEETURL'
  ],
  // 2: at-a-glance
  [
    'SHARECLASSNAME',
    'TANUMBER',
    'TICKER',
    'DAILYFACTOR',
    'ONEDAYYIELD',
    'SEVENDAYCURRENTYIELD',
    'SEVENDAYPREWAIVERYIELD',
    'SEVENDAYEFFECTIVEYIELD',
    'THIRTYDAYCURRENTYIELD',
    'THIRTYDAYEFFECTIVEYIELD',
    'DAILYWEIGHTEDAVERAGEMATURITY',
    'MININITIALINVESTMENT',
    'FACTSHEETURL'
  ],
  // 3: rate-sheet
  [
    'TANUMBER',
    'TICKER',
    'DAILYFACTOR',
    'DAILYNAV', //
    'AVERAGEEFFECTIVEDURATION', //
    'ONEDAYYIELD',
    'SEVENDAYCURRENTYIELD',
    'THIRTYDAYSECYIELD', //
    'THIRTYDAYCURRENTYIELD',
    'THIRTYDAYEFFECTIVEYIELD',
    'MONTHLYONEYEARCUMULATIVE',
    'MONTHLYFIVEYEARANNUALIZED',
    'MONTHLYTENYEARANNUALIZED',
    'MONTHLYSINCEINCEPTION',
    'FACTSHEETURL'
  ],
  // 4: stagecoach-sweep
  [
    'FUNDNAME_SHARECLASSNAME',
    'DAILYFACTOR',
    'ONEDAYYIELD',
    'SEVENDAYCURRENTYIELD',
    'SEVENDAYPREWAIVERYIELD',
    'SEVENDAYEFFECTIVEYIELD',
    'FACTSHEETURL',
    'SUMMARYPROSPECTUSURL',
    'PROSPECTUSURL',
    'ANNUALREPORTURL'
  ]
]

const tableHeaders = new Map<TableTypesEnum, string[]>([
  [TableTypesEnum.CORPORATE_TRUST_SERVICES, headerConfigsArr[0]],
  [TableTypesEnum.GIB, headerConfigsArr[1]],
  [TableTypesEnum.AT_A_GLANCE, headerConfigsArr[2]],
  [TableTypesEnum.RATE_SHEET, headerConfigsArr[3]],
  [TableTypesEnum.STAGECOACH_SWEEP, headerConfigsArr[4]]
])

export default tableHeaders
